# Generated by Django 4.0.4 on 2022-10-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplemodel',
            old_name='num',
            new_name='number',
        ),
    ]
