# Generated by Django 4.0.4 on 2022-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_datamodel_fname_alter_datamodel_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='fname',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='lname',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
